---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 李俊毅.
--- DateTime: 2025/7/17 19:32
---
--1.参数设置
--1.1.优惠倦id
local voucherId =ARGV[1]
--1.2.用户id
local userId = ARGV[2]

--2.数据key
--2.1库存key
local stockKey = 'seckill:stock:' .. voucherId
--2.2订单key
local orderKey = 'seckill:order:' .. voucherId

--3.脚本逻辑
--3.1判断库存是否充足
if(tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end

--3.2判断用户是否下单 若订单键存在（返回值为 1），说明用户已经下过单，返回 2 表示用户已下单
if(redis.call('sismember',orderKey,userId) == 1) then
    return 2
end

--3.3扣减库存
redis.call('incrby',stockKey,-1)

--3.4保存订单
redis.call('sadd',orderKey,userId)

--3.5返回结果
return 0



