---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 李俊毅.
--- DateTime: 2025/7/17 14:46
---比较key对应的value是否相等
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0